name: P3 CI [source_parsers]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my-job:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CI build
      env:
        TEST_ENV: test
        TRAMPOLINE_BUILD_FILE: ci-cd/p3_temp/test_ast_parser.sh
        TRAMPOLINE_IMAGE: gcr.io/cloud-devrel-public-resources/docker-ci-helper/python
      run: ${GITHUB_WORKSPACE}/ci-cd/trampoline_v2.sh
